ALTER TABLE archetype_definitions DROP CONSTRAINT IF EXISTS archetype_definitions_archetype_check;
ALTER TABLE deck_validation_rules DROP CONSTRAINT IF EXISTS deck_validation_rules_archetype_check;
ALTER TABLE match_history DROP CONSTRAINT IF EXISTS match_history_opponent_archetype_check;
ALTER TABLE players DROP CONSTRAINT IF EXISTS players_preferred_archetype_check;
ALTER TABLE cards DROP CONSTRAINT IF EXISTS cards_type_check;

INSERT INTO cards (name, elixir_cost, type) VALUES
('Archers', 3, 'GROUND_TROOP'),
('Archer Queen', 5, 'GROUND_TROOP'),
('Arrows', 3, 'SPELL'),
('Baby Dragon', 4, 'AIR_TROOP'),
('Balloon', 5, 'AIR_TROOP'),
('Bandit', 3, 'GROUND_TROOP'),
('Barbarian Barrel', 2, 'SPELL'),
('Barbarian Hut', 6, 'BUILDING'),
('Barbarians', 5, 'GROUND_TROOP'),
('Bats', 2, 'AIR_TROOP'),
('Battle Healer', 4, 'GROUND_TROOP'),
('Battle Ram', 4, 'GROUND_TROOP'),
('Berserker', 2, 'GROUND_TROOP'),
('Bomb Tower', 4, 'BUILDING'),
('Bomber', 2, 'GROUND_TROOP'),
('Boss Bandit', 6, 'GROUND_TROOP'),
('Bowler', 5, 'GROUND_TROOP'),
('Cannon', 3, 'BUILDING'),
('Cannon Cart', 5, 'GROUND_TROOP'),
('Clone', 3, 'SPELL'),
('Dark Prince', 4, 'GROUND_TROOP'),
('Dart Goblin', 3, 'GROUND_TROOP'),
('Earthquake', 3, 'SPELL'),
('Electro Dragon', 5, 'AIR_TROOP'),
('Electro Giant', 7, 'GROUND_TROOP'),
('Electro Spirit', 1, 'GROUND_TROOP'),
('Electro Wizard', 4, 'GROUND_TROOP'),
('Elite Barbarians', 6, 'GROUND_TROOP'),
('Elixir Collector', 6, 'BUILDING'),
('Elixir Golem', 3, 'GROUND_TROOP'),
('Executioner', 5, 'GROUND_TROOP'),
('Fire Spirit', 1, 'GROUND_TROOP'),
('Fireball', 4, 'SPELL'),
('Firecracker', 3, 'GROUND_TROOP'),
('Fisherman', 3, 'GROUND_TROOP'),
('Flying Machine', 4, 'AIR_TROOP'),
('Freeze', 4, 'SPELL'),
('Furnace', 4, 'BUILDING'),
('Giant', 5, 'GROUND_TROOP'),
('Giant Skeleton', 6, 'GROUND_TROOP'),
('Giant Snowball', 2, 'SPELL'),
('Goblin Barrel', 3, 'SPELL'),
('Goblin Cage', 4, 'BUILDING'),
('Goblin Curse', 2, 'SPELL'),
('Goblin Demolisher', 4, 'GROUND_TROOP'),
('Goblin Drill', 4, 'BUILDING'),
('Goblin Gang', 3, 'GROUND_TROOP'),
('Goblin Giant', 6, 'GROUND_TROOP'),
('Goblin Hut', 5, 'BUILDING'),
('Goblin Machine', 5, 'GROUND_TROOP'),
('Goblins', 2, 'GROUND_TROOP'),
('Goblinstein', 5, 'GROUND_TROOP'),
('Golden Knight', 4, 'GROUND_TROOP'),
('Golem', 8, 'GROUND_TROOP'),
('Graveyard', 5, 'SPELL'),
('Guards', 3, 'GROUND_TROOP'),
('Heal Spirit', 1, 'GROUND_TROOP'),
('Hog Rider', 4, 'GROUND_TROOP'),
('Hunter', 4, 'GROUND_TROOP'),
('Ice Golem', 2, 'GROUND_TROOP'),
('Ice Spirit', 1, 'GROUND_TROOP'),
('Ice Wizard', 3, 'GROUND_TROOP'),
('Inferno Dragon', 4, 'AIR_TROOP'),
('Inferno Tower', 5, 'BUILDING'),
('Knight', 3, 'GROUND_TROOP'),
('Lava Hound', 7, 'AIR_TROOP'),
('Lightning', 6, 'SPELL'),
('Little Prince', 3, 'GROUND_TROOP'),
('Lumberjack', 4, 'GROUND_TROOP'),
('Magic Archer', 4, 'GROUND_TROOP'),
('Mega Knight', 7, 'GROUND_TROOP'),
('Mega Minion', 3, 'AIR_TROOP'),
('Mighty Miner', 4, 'GROUND_TROOP'),
('Miner', 3, 'GROUND_TROOP'),
('Mini P.E.K.K.A', 4, 'GROUND_TROOP'),
('Minion Horde', 5, 'AIR_TROOP'),
('Minions', 3, 'AIR_TROOP'),
('Mirror', 1.5, 'SPELL'),
('Monk', 5, 'GROUND_TROOP'),
('Mortar', 4, 'BUILDING'),
('Mother Witch', 4, 'GROUND_TROOP'),
('Musketeer', 4, 'GROUND_TROOP'),
('Night Witch', 4, 'GROUND_TROOP'),
('P.E.K.K.A', 7, 'GROUND_TROOP'),
('Phoenix', 4, 'AIR_TROOP'),
('Poison', 4, 'SPELL'),
('Prince', 5, 'GROUND_TROOP'),
('Princess', 3, 'GROUND_TROOP'),
('Ram Rider', 5, 'GROUND_TROOP'),
('Rage', 2, 'SPELL'),
('Rascals', 5, 'GROUND_TROOP'),
('Rocket', 6, 'SPELL'),
('Royal Delivery', 3, 'SPELL'),
('Royal Ghost', 3, 'GROUND_TROOP'),
('Royal Giant', 6, 'GROUND_TROOP'),
('Royal Hogs', 5, 'GROUND_TROOP'),
('Royal Recruits', 7, 'GROUND_TROOP'),
('Rune Giant', 4, 'GROUND_TROOP'),
('Skeleton Army', 3, 'GROUND_TROOP'),
('Skeleton Barrel', 3, 'AIR_TROOP'),
('Skeleton Dragons', 4, 'AIR_TROOP'),
('Skeleton King', 4, 'GROUND_TROOP'),
('Skeletons', 1, 'GROUND_TROOP'),
('Sparky', 6, 'GROUND_TROOP'),
('Spear Goblins', 2, 'GROUND_TROOP'),
('Spirit Empress', 3, 'GROUND_TROOP'),
('Suspicious Bush', 2, 'GROUND_TROOP'),
('Tesla', 4, 'BUILDING'),
('The Log', 2, 'SPELL'),
('Three Musketeers', 9, 'GROUND_TROOP'),
('Tombstone', 3, 'BUILDING'),
('Tornado', 3, 'SPELL'),
('Valkyrie', 4, 'GROUND_TROOP'),
('Vines', 3, 'SPELL'),
('Void', 3, 'SPELL'),
('Wall Breakers', 2, 'GROUND_TROOP'),
('Witch', 5, 'GROUND_TROOP'),
('Wizard', 5, 'GROUND_TROOP'),
('X-Bow', 6, 'BUILDING'),
('Zap', 2, 'SPELL'),
('Zappies', 4, 'GROUND_TROOP')
ON CONFLICT (name) DO UPDATE SET
    elixir_cost = EXCLUDED.elixir_cost,
    type = EXCLUDED.type;

UPDATE cards AS c
SET image_asset_id = v.image_asset_id
FROM (VALUES
('Archers', 1),
('Archer Queen', 2),
('Arrows', 3),
('Baby Dragon', 4),
('Balloon', 5),
('Bandit', 6),
('Barbarian Barrel', 7),
('Barbarian Hut', 8),
('Barbarians', 9),
('Bats', 10),
('Battle Healer', 11),
('Battle Ram', 12),
('Berserker', 13),
('Bomb Tower', 14),
('Bomber', 15),
('Boss Bandit', 16),
('Bowler', 17),
('Cannon', 18),
('Cannon Cart', 19),
('Clone', 20),
('Dark Prince', 21),
('Dart Goblin', 22),
('Earthquake', 23),
('Electro Dragon', 24),
('Electro Giant', 25),
('Electro Spirit', 26),
('Electro Wizard', 27),
('Elite Barbarians', 28),
('Elixir Collector', 29),
('Elixir Golem', 30),
('Executioner', 31),
('Fire Spirit', 32),
('Fireball', 33),
('Firecracker', 34),
('Fisherman', 35),
('Flying Machine', 36),
('Freeze', 37),
('Furnace', 38),
('Giant', 39),
('Giant Skeleton', 40),
('Giant Snowball', 41),
('Goblin Barrel', 42),
('Goblin Cage', 43),
('Goblin Curse', 44),
('Goblin Demolisher', 45),
('Goblin Drill', 46),
('Goblin Gang', 47),
('Goblin Giant', 48),
('Goblin Hut', 49),
('Goblin Machine', 50),
('Goblins', 51),
('Goblinstein', 52),
('Golden Knight', 53),
('Golem', 54),
('Graveyard', 55),
('Guards', 56),
('Heal Spirit', 57),
('Hog Rider', 58),
('Hunter', 59),
('Ice Golem', 60),
('Ice Spirit', 61),
('Ice Wizard', 62),
('Inferno Dragon', 63),
('Inferno Tower', 64),
('Knight', 65),
('Lava Hound', 66),
('Lightning', 67),
('Little Prince', 68),
('Lumberjack', 69),
('Magic Archer', 70),
('Mega Knight', 71),
('Mega Minion', 72),
('Mighty Miner', 73),
('Miner', 74),
('Mini P.E.K.K.A', 75),
('Minion Horde', 76),
('Minions', 77),
('Mirror', 78),
('Monk', 79),
('Mortar', 80),
('Mother Witch', 81),
('Musketeer', 82),
('Night Witch', 83),
('P.E.K.K.A', 84),
('Phoenix', 85),
('Poison', 86),
('Prince', 87),
('Princess', 88),
('Ram Rider', 89),
('Rage', 90),
('Rascals', 91),
('Rocket', 92),
('Royal Delivery', 93),
('Royal Ghost', 94),
('Royal Giant', 95),
('Royal Hogs', 96),
('Royal Recruits', 97),
('Rune Giant', 98),
('Skeleton Army', 99),
('Skeleton Barrel', 100),
('Skeleton Dragons', 101),
('Skeleton King', 102),
('Skeletons', 103),
('Sparky', 104),
('Spear Goblins', 105),
('Spirit Empress', 106),
('Suspicious Bush', 107),
('Tesla', 108),
('The Log', 109),
('Three Musketeers', 110),
('Tombstone', 111),
('Tornado', 112),
('Valkyrie', 113),
('Vines', 114),
('Void', 115),
('Wall Breakers', 116),
('Witch', 117),
('Wizard', 118),
('X-Bow', 119),
('Zap', 120),
('Zappies', 121)
) AS v(card_name, image_asset_id)
WHERE c.name = v.card_name;

INSERT INTO card_roles (card_id, role)
SELECT c.id, v.role
FROM (VALUES
('Archers','ANTI_AIR'),('Archers','SUPPORT'),
('Archer Queen','ANTI_AIR'),('Archer Queen','SINGLE_TARGET_DPS'),('Archer Queen','SUPPORT'),
('Arrows','SMALL_SPELL'),('Arrows','AIR_SUPPORT_COUNTER'),
('Baby Dragon','ANTI_AIR'),('Baby Dragon','SPLASH_SUPPORT'),('Baby Dragon','SUPPORT'),('Baby Dragon','AIR_SUPPORT_COUNTER'),
('Balloon','WIN_CONDITION'),('Balloon','PRESSURE'),
('Bandit','PRESSURE'),('Bandit','SUPPORT'),
('Barbarian Barrel','SMALL_SPELL'),('Barbarian Barrel','SUPPORT'),
('Barbarian Hut','BUILDING'),
('Barbarians','SWARM'),('Barbarians','SINGLE_TARGET_DPS'),
('Bats','ANTI_AIR'),('Bats','SWARM'),('Bats','CYCLE'),
('Battle Healer','SUPPORT'),
('Battle Ram','WIN_CONDITION'),('Battle Ram','PRESSURE'),
('Berserker','CYCLE'),('Berserker','SINGLE_TARGET_DPS'),
('Bomb Tower','BUILDING'),('Bomb Tower','SPLASH_SUPPORT'),
('Bomber','CYCLE'),('Bomber','SPLASH_SUPPORT'),
('Boss Bandit','PRESSURE'),('Boss Bandit','SINGLE_TARGET_DPS'),
('Bowler','SPLASH_SUPPORT'),('Bowler','SUPPORT'),
('Cannon','BUILDING'),('Cannon','SINGLE_TARGET_DPS'),
('Cannon Cart','SINGLE_TARGET_DPS'),('Cannon Cart','SUPPORT'),
('Clone','BIG_SPELL'),
('Dark Prince','SPLASH_SUPPORT'),('Dark Prince','PRESSURE'),
('Dart Goblin','ANTI_AIR'),('Dart Goblin','SINGLE_TARGET_DPS'),('Dart Goblin','SUPPORT'),
('Earthquake','BIG_SPELL'),
('Electro Dragon','ANTI_AIR'),('Electro Dragon','SPLASH_SUPPORT'),('Electro Dragon','AIR_SUPPORT_COUNTER'),
('Electro Giant','WIN_CONDITION'),('Electro Giant','TANK'),
('Electro Spirit','CYCLE'),('Electro Spirit','ANTI_AIR'),('Electro Spirit','AIR_SUPPORT_COUNTER'),
('Electro Wizard','ANTI_AIR'),('Electro Wizard','SINGLE_TARGET_DPS'),('Electro Wizard','AIR_SUPPORT_COUNTER'),
('Elite Barbarians','PRESSURE'),('Elite Barbarians','SINGLE_TARGET_DPS'),
('Elixir Collector','BUILDING'),
('Elixir Golem','WIN_CONDITION'),('Elixir Golem','TANK'),
('Executioner','ANTI_AIR'),('Executioner','SPLASH_SUPPORT'),('Executioner','AIR_SUPPORT_COUNTER'),
('Fire Spirit','CYCLE'),('Fire Spirit','SPLASH_SUPPORT'),
('Fireball','BIG_SPELL'),('Fireball','AIR_SUPPORT_COUNTER'),
('Firecracker','ANTI_AIR'),('Firecracker','SPLASH_SUPPORT'),('Firecracker','AIR_SUPPORT_COUNTER'),
('Fisherman','SUPPORT'),('Fisherman','SINGLE_TARGET_DPS'),
('Flying Machine','ANTI_AIR'),('Flying Machine','SINGLE_TARGET_DPS'),('Flying Machine','SUPPORT'),
('Freeze','BIG_SPELL'),
('Furnace','BUILDING'),('Furnace','SPLASH_SUPPORT'),
('Giant','WIN_CONDITION'),('Giant','TANK'),
('Giant Skeleton','TANK'),('Giant Skeleton','SPLASH_SUPPORT'),
('Giant Snowball','SMALL_SPELL'),('Giant Snowball','AIR_SUPPORT_COUNTER'),
('Goblin Barrel','WIN_CONDITION'),('Goblin Barrel','PRESSURE'),
('Goblin Cage','BUILDING'),('Goblin Cage','SINGLE_TARGET_DPS'),
('Goblin Curse','SMALL_SPELL'),
('Goblin Demolisher','SPLASH_SUPPORT'),('Goblin Demolisher','PRESSURE'),
('Goblin Drill','WIN_CONDITION'),('Goblin Drill','BUILDING'),('Goblin Drill','PRESSURE'),
('Goblin Gang','SWARM'),('Goblin Gang','SINGLE_TARGET_DPS'),
('Goblin Giant','WIN_CONDITION'),('Goblin Giant','TANK'),('Goblin Giant','ANTI_AIR'),
('Goblin Hut','BUILDING'),('Goblin Hut','ANTI_AIR'),
('Goblin Machine','SPLASH_SUPPORT'),('Goblin Machine','PRESSURE'),
('Goblins','CYCLE'),('Goblins','SWARM'),('Goblins','SINGLE_TARGET_DPS'),
('Goblinstein','WIN_CONDITION'),('Goblinstein','TANK'),('Goblinstein','SUPPORT'),
('Golden Knight','PRESSURE'),('Golden Knight','SUPPORT'),
('Golem','WIN_CONDITION'),('Golem','TANK'),
('Graveyard','WIN_CONDITION'),
('Guards','SWARM'),('Guards','SINGLE_TARGET_DPS'),
('Heal Spirit','CYCLE'),('Heal Spirit','SUPPORT'),
('Hog Rider','WIN_CONDITION'),('Hog Rider','PRESSURE'),
('Hunter','ANTI_AIR'),('Hunter','SINGLE_TARGET_DPS'),('Hunter','AIR_SUPPORT_COUNTER'),
('Ice Golem','CYCLE'),('Ice Golem','TANK'),
('Ice Spirit','CYCLE'),('Ice Spirit','ANTI_AIR'),('Ice Spirit','AIR_SUPPORT_COUNTER'),
('Ice Wizard','ANTI_AIR'),('Ice Wizard','SPLASH_SUPPORT'),('Ice Wizard','SUPPORT'),('Ice Wizard','AIR_SUPPORT_COUNTER'),
('Inferno Dragon','ANTI_AIR'),('Inferno Dragon','SINGLE_TARGET_DPS'),('Inferno Dragon','AIR_SUPPORT_COUNTER'),
('Inferno Tower','BUILDING'),('Inferno Tower','SINGLE_TARGET_DPS'),('Inferno Tower','AIR_SUPPORT_COUNTER'),
('Knight','CYCLE'),('Knight','SUPPORT'),
('Lava Hound','WIN_CONDITION'),('Lava Hound','TANK'),('Lava Hound','ANTI_AIR'),
('Lightning','BIG_SPELL'),('Lightning','AIR_SUPPORT_COUNTER'),
('Little Prince','ANTI_AIR'),('Little Prince','SINGLE_TARGET_DPS'),('Little Prince','SUPPORT'),
('Lumberjack','SUPPORT'),('Lumberjack','SINGLE_TARGET_DPS'),
('Magic Archer','ANTI_AIR'),('Magic Archer','SPLASH_SUPPORT'),('Magic Archer','AIR_SUPPORT_COUNTER'),
('Mega Knight','TANK'),('Mega Knight','SPLASH_SUPPORT'),('Mega Knight','PRESSURE'),
('Mega Minion','ANTI_AIR'),('Mega Minion','SINGLE_TARGET_DPS'),('Mega Minion','SUPPORT'),
('Mighty Miner','SINGLE_TARGET_DPS'),('Mighty Miner','SUPPORT'),
('Miner','WIN_CONDITION'),('Miner','PRESSURE'),
('Mini P.E.K.K.A','SINGLE_TARGET_DPS'),('Mini P.E.K.K.A','SUPPORT'),
('Minion Horde','ANTI_AIR'),('Minion Horde','SWARM'),('Minion Horde','AIR_SUPPORT_COUNTER'),
('Minions','ANTI_AIR'),('Minions','SWARM'),('Minions','AIR_SUPPORT_COUNTER'),
('Mirror','BIG_SPELL'),
('Monk','TANK'),('Monk','SUPPORT'),
('Mortar','WIN_CONDITION'),('Mortar','BUILDING'),('Mortar','SIEGE'),
('Mother Witch','ANTI_AIR'),('Mother Witch','SPLASH_SUPPORT'),('Mother Witch','SUPPORT'),
('Musketeer','ANTI_AIR'),('Musketeer','SINGLE_TARGET_DPS'),('Musketeer','SUPPORT'),
('Night Witch','SUPPORT'),('Night Witch','SWARM'),
('P.E.K.K.A','TANK'),('P.E.K.K.A','SINGLE_TARGET_DPS'),
('Phoenix','ANTI_AIR'),('Phoenix','SINGLE_TARGET_DPS'),('Phoenix','AIR_SUPPORT_COUNTER'),
('Poison','BIG_SPELL'),
('Prince','PRESSURE'),('Prince','SINGLE_TARGET_DPS'),
('Princess','ANTI_AIR'),('Princess','SPLASH_SUPPORT'),('Princess','SWARM'),
('Ram Rider','WIN_CONDITION'),('Ram Rider','PRESSURE'),('Ram Rider','SINGLE_TARGET_DPS'),
('Rage','SMALL_SPELL'),
('Rascals','ANTI_AIR'),('Rascals','SWARM'),('Rascals','SUPPORT'),
('Rocket','BIG_SPELL'),('Rocket','AIR_SUPPORT_COUNTER'),
('Royal Delivery','SMALL_SPELL'),('Royal Delivery','AIR_SUPPORT_COUNTER'),
('Royal Ghost','PRESSURE'),('Royal Ghost','SPLASH_SUPPORT'),
('Royal Giant','WIN_CONDITION'),('Royal Giant','TANK'),
('Royal Hogs','WIN_CONDITION'),('Royal Hogs','PRESSURE'),
('Royal Recruits','SWARM'),('Royal Recruits','TANK'),
('Rune Giant','TANK'),('Rune Giant','SUPPORT'),
('Skeleton Army','SWARM'),('Skeleton Army','SINGLE_TARGET_DPS'),
('Skeleton Barrel','WIN_CONDITION'),('Skeleton Barrel','PRESSURE'),
('Skeleton Dragons','ANTI_AIR'),('Skeleton Dragons','SPLASH_SUPPORT'),('Skeleton Dragons','AIR_SUPPORT_COUNTER'),
('Skeleton King','TANK'),('Skeleton King','SWARM'),
('Skeletons','CYCLE'),('Skeletons','SWARM'),
('Sparky','SPLASH_SUPPORT'),('Sparky','SINGLE_TARGET_DPS'),
('Spear Goblins','ANTI_AIR'),('Spear Goblins','CYCLE'),('Spear Goblins','SUPPORT'),
('Spirit Empress','ANTI_AIR'),('Spirit Empress','SINGLE_TARGET_DPS'),('Spirit Empress','SUPPORT'),
('Suspicious Bush','CYCLE'),('Suspicious Bush','PRESSURE'),
('Tesla','BUILDING'),('Tesla','ANTI_AIR'),('Tesla','SINGLE_TARGET_DPS'),('Tesla','AIR_SUPPORT_COUNTER'),
('The Log','SMALL_SPELL'),
('Three Musketeers','ANTI_AIR'),('Three Musketeers','SINGLE_TARGET_DPS'),('Three Musketeers','SUPPORT'),
('Tombstone','BUILDING'),('Tombstone','SWARM'),
('Tornado','BIG_SPELL'),('Tornado','AIR_SUPPORT_COUNTER'),
('Valkyrie','SPLASH_SUPPORT'),('Valkyrie','SUPPORT'),
('Vines','BIG_SPELL'),('Vines','AIR_SUPPORT_COUNTER'),
('Void','BIG_SPELL'),('Void','AIR_SUPPORT_COUNTER'),
('Wall Breakers','WIN_CONDITION'),('Wall Breakers','PRESSURE'),('Wall Breakers','CYCLE'),
('Witch','ANTI_AIR'),('Witch','SPLASH_SUPPORT'),('Witch','SWARM'),
('Wizard','ANTI_AIR'),('Wizard','SPLASH_SUPPORT'),('Wizard','AIR_SUPPORT_COUNTER'),
('X-Bow','WIN_CONDITION'),('X-Bow','BUILDING'),('X-Bow','SIEGE'),
('Zap','SMALL_SPELL'),('Zap','AIR_SUPPORT_COUNTER'),
('Zappies','ANTI_AIR'),('Zappies','SINGLE_TARGET_DPS'),('Zappies','AIR_SUPPORT_COUNTER')
) AS v(card_name, role)
JOIN cards c ON c.name = v.card_name
WHERE NOT EXISTS (
    SELECT 1 FROM card_roles existing
    WHERE existing.card_id = c.id AND existing.role = v.role
);

UPDATE archetype_definitions existing
SET description = v.description,
    min_average_elixir = v.min_average_elixir,
    max_average_elixir = v.max_average_elixir
FROM (VALUES
('CYCLE', 'Fast low-elixir pressure decks that repeatedly return to a cheap win condition such as Hog Rider, Goblin Drill, Miner, Wall Breakers, or Goblin Barrel.', 2.3, 3.4),
('CONTROL', 'Reactive decks that defend efficiently, gain positive trades, and convert surviving troops or spells into counterpressure.', 2.8, 4.0),
('BEATDOWN', 'Tank-centered decks that build large pushes behind Giant, Golem, Lava Hound, Electro Giant, Goblin Giant, or similar heavy threats.', 3.6, 5.0),
('BAIT', 'Pressure decks built around several cards that force the same spell or response, then punish when that response is out of cycle.', 2.8, 3.8),
('BRIDGE_SPAM', 'Aggressive pressure decks using fast lane threats to force awkward responses and punish elixir gaps.', 3.0, 4.1),
('SIEGE', 'Building win-condition decks that pressure from the player side of the arena with X-Bow or Mortar.', 2.8, 4.0),
('AIR_COUNTER', 'Adapted deck plan that prioritizes reliable anti-air and answers to air-support-heavy opponents.', 2.8, 4.2)
) AS v(archetype, description, min_average_elixir, max_average_elixir)
WHERE existing.archetype = v.archetype;

INSERT INTO archetype_definitions (archetype, description, min_average_elixir, max_average_elixir)
SELECT v.archetype, v.description, v.min_average_elixir, v.max_average_elixir
FROM (VALUES
('CYCLE', 'Fast low-elixir pressure decks that repeatedly return to a cheap win condition such as Hog Rider, Goblin Drill, Miner, Wall Breakers, or Goblin Barrel.', 2.3, 3.4),
('CONTROL', 'Reactive decks that defend efficiently, gain positive trades, and convert surviving troops or spells into counterpressure.', 2.8, 4.0),
('BEATDOWN', 'Tank-centered decks that build large pushes behind Giant, Golem, Lava Hound, Electro Giant, Goblin Giant, or similar heavy threats.', 3.6, 5.0),
('BAIT', 'Pressure decks built around several cards that force the same spell or response, then punish when that response is out of cycle.', 2.8, 3.8),
('BRIDGE_SPAM', 'Aggressive pressure decks using fast lane threats to force awkward responses and punish elixir gaps.', 3.0, 4.1),
('SIEGE', 'Building win-condition decks that pressure from the player side of the arena with X-Bow or Mortar.', 2.8, 4.0),
('AIR_COUNTER', 'Adapted deck plan that prioritizes reliable anti-air and answers to air-support-heavy opponents.', 2.8, 4.2)
) AS v(archetype, description, min_average_elixir, max_average_elixir)
WHERE NOT EXISTS (
    SELECT 1 FROM archetype_definitions existing
    WHERE existing.archetype = v.archetype
);

INSERT INTO archetype_required_roles (archetype_definition_id, role)
SELECT a.id, v.role
FROM (VALUES
('CYCLE','WIN_CONDITION'),('CYCLE','SMALL_SPELL'),('CYCLE','CYCLE'),('CYCLE','BUILDING'),
('CONTROL','WIN_CONDITION'),('CONTROL','SMALL_SPELL'),('CONTROL','BIG_SPELL'),('CONTROL','SINGLE_TARGET_DPS'),
('BEATDOWN','WIN_CONDITION'),('BEATDOWN','TANK'),('BEATDOWN','SUPPORT'),('BEATDOWN','BIG_SPELL'),
('BAIT','WIN_CONDITION'),('BAIT','SWARM'),('BAIT','SMALL_SPELL'),('BAIT','PRESSURE'),
('BRIDGE_SPAM','WIN_CONDITION'),('BRIDGE_SPAM','PRESSURE'),('BRIDGE_SPAM','SINGLE_TARGET_DPS'),('BRIDGE_SPAM','BIG_SPELL'),
('SIEGE','WIN_CONDITION'),('SIEGE','SIEGE'),('SIEGE','BUILDING'),('SIEGE','SMALL_SPELL'),
('AIR_COUNTER','ANTI_AIR'),('AIR_COUNTER','AIR_SUPPORT_COUNTER'),('AIR_COUNTER','SMALL_SPELL'),('AIR_COUNTER','SINGLE_TARGET_DPS')
) AS v(archetype, role)
JOIN archetype_definitions a ON a.archetype = v.archetype
WHERE NOT EXISTS (
    SELECT 1 FROM archetype_required_roles existing
    WHERE existing.archetype_definition_id = a.id AND existing.role = v.role
);

INSERT INTO deck_validation_rules (code, description, archetype, active)
SELECT v.code, v.description, v.archetype, true
FROM (VALUES
('EXACTLY_EIGHT_CARDS', 'Deck must contain exactly 8 cards.', NULL),
('EXACTLY_ONE_WIN_CONDITION', 'Deck must contain exactly one main win condition.', NULL),
('REQUIRES_SMALL_SPELL', 'Deck must contain at least one small spell.', NULL),
('REQUIRES_TANK_ANSWER', 'Deck must contain a reliable tank answer or high single-target DPS.', NULL),
('AIR_WEAKNESS_REQUIRES_TWO_AA', 'Players weak against air require at least two anti-air cards.', NULL),
('AVERAGE_ELIXIR_LIMIT', 'Average elixir must match player habits and selected archetype.', NULL),
('CYCLE_AVERAGE_ELIXIR_RANGE', 'Cycle decks should stay low-cost and include cheap support/cycle cards.', 'CYCLE'),
('BEATDOWN_REQUIRES_TANK_SUPPORT', 'Beatdown decks must include a tank, support, and spell coverage.', 'BEATDOWN'),
('BAIT_REQUIRES_MULTIPLE_SPELL_BAIT_CARDS', 'Bait decks should contain multiple cards that stress the same response.', 'BAIT'),
('SIEGE_REQUIRES_BUILDING_WIN_CONDITION', 'Siege decks must contain X-Bow or Mortar-style building win condition.', 'SIEGE'),
('AIR_COUNTER_REQUIRES_AIR_SUPPORT_ANSWER', 'Air counter decks must include anti-air and an answer to air support.', 'AIR_COUNTER')
) AS v(code, description, archetype)
WHERE NOT EXISTS (
    SELECT 1 FROM deck_validation_rules existing
    WHERE existing.code = v.code
);

INSERT INTO card_synergies (card_a_id, card_b_id, type, weight, explanation)
SELECT a.id, b.id, v.type, v.weight, v.explanation
FROM (VALUES
('Hog Rider','Earthquake','SYNERGY',10,'Earthquake clears buildings that stop Hog Rider.'),
('Hog Rider','Ice Spirit','SYNERGY',6,'Ice Spirit supports cheap Hog cycle pressure and freezes defenders.'),
('Hog Rider','Cannon','SYNERGY',5,'Cannon gives Hog cycle a cheap defensive building.'),
('Goblin Drill','Wall Breakers','SYNERGY',8,'Drill and Wall Breakers create split-lane pressure in cycle decks.'),
('Goblin Drill','Fireball','SYNERGY',6,'Fireball removes medium troops defending Goblin Drill.'),
('Goblin Barrel','Princess','SYNERGY',9,'Princess baits small spells that would otherwise answer Goblin Barrel.'),
('Goblin Barrel','Goblin Gang','SYNERGY',8,'Goblin Gang and Barrel overload Log/Zap responses.'),
('Goblin Barrel','The Log','SYNERGY',5,'The Log supports bait mirrors and cheap ground control.'),
('Miner','Wall Breakers','SYNERGY',9,'Miner tanks while Wall Breakers threaten tower damage.'),
('Miner','Poison','SYNERGY',8,'Miner Poison converts defensive trades into chip damage.'),
('Golem','Night Witch','SYNERGY',10,'Night Witch supports Golem pushes with sustained pressure.'),
('Golem','Lightning','SYNERGY',8,'Lightning removes defensive buildings and high-value anti-tank troops.'),
('Lava Hound','Balloon','SYNERGY',10,'Lava Hound tanks for Balloon in air beatdown pushes.'),
('Lava Hound','Miner','SYNERGY',7,'Miner tanks for Lava Pups and supports air chip pressure.'),
('Royal Giant','Lightning','SYNERGY',8,'Lightning clears buildings and ranged defenders for Royal Giant.'),
('Giant','Graveyard','SYNERGY',8,'Giant tanks tower fire while Graveyard creates skeleton pressure.'),
('Electro Giant','Tornado','SYNERGY',9,'Tornado pulls troops into Electro Giant reflection range.'),
('Bowler','Graveyard','SYNERGY',7,'Bowler defends ground pushes and tanks counterpush Graveyard.'),
('Executioner','Tornado','SYNERGY',10,'Tornado groups units for Executioner splash damage.'),
('Magic Archer','Tornado','SYNERGY',8,'Tornado lines up Magic Archer pierce damage.'),
('X-Bow','Tesla','SYNERGY',9,'Tesla protects X-Bow from tanks and air pressure.'),
('Mortar','Miner','SYNERGY',7,'Miner tanks and chips while Mortar pressures from range.'),
('Battle Ram','Bandit','SYNERGY',8,'Bandit and Battle Ram create bridge spam pressure.'),
('Ram Rider','Lightning','SYNERGY',7,'Lightning clears high-value defenders for Ram Rider.'),
('P.E.K.K.A','Battle Ram','SYNERGY',8,'P.E.K.K.A defends tanks while Battle Ram counterpressures.'),
('Firecracker','Tornado','SYNERGY',7,'Tornado improves Firecracker splash value against grouped troops.'),
('Inferno Tower','The Log','SYNERGY',5,'The Log clears swarms that reset or distract Inferno Tower.'),
('Inferno Dragon','Zap','COUNTER_SYNERGY',-6,'Zap resets Inferno Dragon ramp-up damage.'),
('Inferno Tower','Zap','COUNTER_SYNERGY',-6,'Zap resets Inferno Tower ramp-up damage.'),
('Sparky','Zap','COUNTER_SYNERGY',-7,'Zap resets Sparky charge.'),
('Sparky','Electro Wizard','COUNTER_SYNERGY',-9,'Electro Wizard repeatedly resets Sparky.'),
('Hog Rider','Golem','COUNTER_SYNERGY',-8,'Fast Hog cycle and heavy Golem beatdown pull the deck in opposite directions.'),
('X-Bow','Golem','COUNTER_SYNERGY',-8,'Siege pressure and heavy beatdown have conflicting deck plans.')
) AS v(card_a, card_b, type, weight, explanation)
JOIN cards a ON a.name = v.card_a
JOIN cards b ON b.name = v.card_b
WHERE NOT EXISTS (
    SELECT 1 FROM card_synergies existing
    WHERE existing.card_a_id = a.id AND existing.card_b_id = b.id
);

INSERT INTO card_synergies (card_a_id, card_b_id, type, weight, explanation)
SELECT a.id, b.id, v.type, v.weight, v.explanation
FROM (VALUES
('Hog Rider','Firecracker','SYNERGY',7,'Firecracker supports Hog Rider by clearing swarms and pressuring air defenders.'),
('Hog Rider','Musketeer','SYNERGY',6,'Musketeer gives Hog cycle reliable air defense and counterpush value.'),
('Hog Rider','Tesla','SYNERGY',6,'Tesla gives cycle decks a flexible anti-air defensive building.'),
('Hog Rider','The Log','SYNERGY',8,'The Log clears cheap ground swarms that stop Hog Rider.'),
('Hog Rider','Giant Snowball','SYNERGY',6,'Giant Snowball delays defenders and supports Hog tower connections.'),
('Hog Rider','Fireball','SYNERGY',7,'Fireball removes medium defenders and supports Hog pressure.'),
('Hog Rider','Zap','SYNERGY',5,'Zap quickly clears or resets cheap Hog counters.'),
('Hog Rider','Skeletons','SYNERGY',5,'Skeletons keep the deck cheap and help return to Hog Rider faster.'),
('Hog Rider','Electro Spirit','SYNERGY',5,'Electro Spirit cycles quickly and helps Hog break through swarms.'),
('Hog Rider','Knight','SYNERGY',5,'Knight provides cheap ground defense in Hog cycle decks.'),
('Goblin Drill','Fire Spirit','SYNERGY',5,'Fire Spirit pressures swarm answers to Goblin Drill.'),
('Goblin Drill','Bomber','SYNERGY',6,'Bomber clears ground swarms that defend Drill.'),
('Goblin Drill','Magic Archer','SYNERGY',7,'Magic Archer punishes predictable Drill defenses with line damage.'),
('Goblin Drill','Poison','SYNERGY',8,'Poison controls troops placed on top of Drill.'),
('Goblin Drill','The Log','SYNERGY',7,'The Log clears Goblins and Skeletons defending Drill.'),
('Goblin Drill','Valkyrie','SYNERGY',6,'Valkyrie tanks and clears ground troops around Drill.'),
('Goblin Drill','Firecracker','SYNERGY',6,'Firecracker punishes grouped Drill defenses from range.'),
('Goblin Drill','Tornado','SYNERGY',5,'Tornado can pull defenders away from Drill pressure.'),
('Goblin Drill','Skeletons','SYNERGY',4,'Skeletons keep Drill cycle cheap and improve defense.'),
('Goblin Drill','Electro Spirit','SYNERGY',4,'Electro Spirit supports Drill cycle and stun pressure.'),
('Goblin Barrel','Rocket','SYNERGY',8,'Rocket supports classic bait by converting tower chip into finishing damage.'),
('Goblin Barrel','Inferno Tower','SYNERGY',7,'Inferno Tower covers tanks while bait cards pressure spells.'),
('Goblin Barrel','Knight','SYNERGY',6,'Knight tanks and defends cheaply in bait decks.'),
('Goblin Barrel','Rascals','SYNERGY',7,'Rascals add spell-bait pressure and defensive coverage.'),
('Goblin Barrel','Dart Goblin','SYNERGY',8,'Dart Goblin baits small spells and provides long-range pressure.'),
('Goblin Barrel','Skeleton Army','SYNERGY',7,'Skeleton Army baits the same small spells that answer Barrel.'),
('Goblin Barrel','Guards','SYNERGY',6,'Guards bait small spells while defending ground threats.'),
('Goblin Barrel','Tesla','SYNERGY',5,'Tesla gives bait decks compact defensive structure.'),
('Goblin Barrel','Fireball','COUNTER_SYNERGY',-4,'Fireball is expensive for classic Barrel bait and can make the deck clunky.'),
('Goblin Barrel','Earthquake','COUNTER_SYNERGY',-5,'Earthquake does not support Barrel bait pressure well.'),
('Miner','Bats','SYNERGY',7,'Miner tanks for Bats and creates cheap pressure.'),
('Miner','Spear Goblins','SYNERGY',6,'Miner tanks while Spear Goblins add chip and air coverage.'),
('Miner','Firecracker','SYNERGY',6,'Miner tanks for Firecracker counterpressure.'),
('Miner','Magic Archer','SYNERGY',7,'Miner pressures while Magic Archer punishes lined-up defenses.'),
('Miner','Mortar','SYNERGY',8,'Miner supports Mortar chip and tanks during siege pressure.'),
('Miner','Skeleton Barrel','SYNERGY',7,'Miner tanks for Skeleton Barrel death spawn pressure.'),
('Miner','Goblin Gang','SYNERGY',6,'Miner pairs with swarm pressure and bait patterns.'),
('Miner','Bomb Tower','SYNERGY',5,'Bomb Tower gives Miner control decks strong ground defense.'),
('Miner','Wall Breakers','SYNERGY',9,'Miner tanks tower shots while Wall Breakers threaten burst damage.'),
('Miner','The Log','SYNERGY',5,'The Log clears cheap ground counters to Miner pressure.'),
('Wall Breakers','Magic Archer','SYNERGY',7,'Magic Archer punishes compact defenses against Wall Breakers.'),
('Wall Breakers','Bomb Tower','SYNERGY',5,'Bomb Tower stabilizes quick Wall Breaker cycle decks.'),
('Wall Breakers','Fireball','SYNERGY',6,'Fireball removes medium defenders against Wall Breaker pressure.'),
('Wall Breakers','Bats','SYNERGY',5,'Bats create cheap split pressure with Wall Breakers.'),
('Wall Breakers','Spear Goblins','SYNERGY',5,'Spear Goblins support cheap dual-lane pressure.'),
('Wall Breakers','Valkyrie','SYNERGY',6,'Valkyrie tanks and clears ground swarms for Wall Breakers.'),
('Giant','Musketeer','SYNERGY',7,'Musketeer supports Giant pushes with air and single-target damage.'),
('Giant','Mini P.E.K.K.A','SYNERGY',6,'Mini P.E.K.K.A protects Giant pushes from tanks and bruisers.'),
('Giant','Prince','SYNERGY',7,'Prince adds high single-target pressure behind Giant.'),
('Giant','Night Witch','SYNERGY',7,'Night Witch adds sustained support behind Giant.'),
('Giant','Minions','SYNERGY',5,'Minions support Giant pushes and defend air.'),
('Giant','Arrows','SYNERGY',6,'Arrows clear swarms that stop Giant support.'),
('Giant','Fireball','SYNERGY',6,'Fireball removes medium defenders against Giant.'),
('Giant','Zap','SYNERGY',5,'Zap resets Inferno effects and clears small swarms for Giant.'),
('Giant','Sparky','SYNERGY',8,'Giant tanks while Sparky threatens major defensive punish.'),
('Giant','Bowler','SYNERGY',6,'Bowler clears ground defenders for Giant pushes.'),
('Golem','Baby Dragon','SYNERGY',8,'Baby Dragon splash protects Golem pushes from swarms.'),
('Golem','Tornado','SYNERGY',8,'Tornado groups defenders for splash units behind Golem.'),
('Golem','Mega Minion','SYNERGY',7,'Mega Minion gives Golem decks cheap air defense and support.'),
('Golem','Lumberjack','SYNERGY',8,'Lumberjack rage increases Golem push pressure.'),
('Golem','Phoenix','SYNERGY',7,'Phoenix supports Golem pushes with durable air pressure.'),
('Golem','Electro Dragon','SYNERGY',7,'Electro Dragon controls Inferno and swarm defenses against Golem.'),
('Golem','Bomber','SYNERGY',5,'Bomber provides cheap ground splash behind Golem.'),
('Golem','Barbarian Barrel','SYNERGY',6,'Barbarian Barrel clears ground swarm pressure for Golem.'),
('Golem','Elixir Collector','SYNERGY',7,'Elixir Collector helps fund expensive Golem pushes.'),
('Golem','Three Musketeers','COUNTER_SYNERGY',-7,'Golem and Three Musketeers make the deck too expensive and awkward.'),
('Lava Hound','Skeleton Dragons','SYNERGY',8,'Skeleton Dragons provide air splash behind Lava Hound.'),
('Lava Hound','Mega Minion','SYNERGY',7,'Mega Minion supports Lava pushes and protects air lanes.'),
('Lava Hound','Flying Machine','SYNERGY',8,'Flying Machine adds long-range air support behind Lava Hound.'),
('Lava Hound','Arrows','SYNERGY',7,'Arrows remove Minions and other swarm answers to Lava pushes.'),
('Lava Hound','Fireball','SYNERGY',7,'Fireball clears medium air defenders against Lava.'),
('Lava Hound','Zap','SYNERGY',5,'Zap supports Balloon or Lava pressure through resets and swarms.'),
('Lava Hound','Tombstone','SYNERGY',6,'Tombstone provides cheap ground defense for Lava decks.'),
('Lava Hound','Barbarians','SYNERGY',6,'Barbarians cover ground defense in Lava decks.'),
('Balloon','Freeze','SYNERGY',9,'Freeze creates high burst potential for Balloon.'),
('Balloon','Lumberjack','SYNERGY',8,'Lumberjack rage accelerates Balloon pressure.'),
('Balloon','Giant Snowball','SYNERGY',7,'Giant Snowball knocks defenders away from Balloon.'),
('Balloon','Miner','SYNERGY',7,'Miner tanks or chips while Balloon pressures tower.'),
('Balloon','Ice Golem','SYNERGY',7,'Ice Golem tanks cheaply for Balloon.'),
('Balloon','Tornado','SYNERGY',6,'Tornado pulls anti-air away from Balloon pathing.'),
('Royal Giant','Fisherman','SYNERGY',9,'Fisherman pulls tanks and defenders away from Royal Giant.'),
('Royal Giant','Hunter','SYNERGY',8,'Hunter covers tanks and air threats in Royal Giant decks.'),
('Royal Giant','Phoenix','SYNERGY',7,'Phoenix adds durable support for Royal Giant pushes.'),
('Royal Giant','Mother Witch','SYNERGY',7,'Mother Witch punishes swarms used to defend Royal Giant.'),
('Royal Giant','Electro Spirit','SYNERGY',5,'Electro Spirit supports cheap cycle and resets.'),
('Royal Giant','The Log','SYNERGY',6,'The Log clears ground swarms against Royal Giant.'),
('Royal Giant','Fireball','SYNERGY',6,'Fireball removes ranged defenders for Royal Giant.'),
('Royal Giant','Earthquake','SYNERGY',7,'Earthquake damages buildings that distract Royal Giant.'),
('Electro Giant','Baby Dragon','SYNERGY',7,'Baby Dragon splash supports Electro Giant pushes.'),
('Electro Giant','Lightning','SYNERGY',8,'Lightning removes buildings and ranged damage against Electro Giant.'),
('Electro Giant','Bomber','SYNERGY',5,'Bomber clears ground swarms behind Electro Giant.'),
('Electro Giant','Phoenix','SYNERGY',7,'Phoenix supports Electro Giant with air pressure.'),
('Electro Giant','Cannon','COUNTER_SYNERGY',-6,'Cannon is a common cheap answer to Electro Giant and does not fit the same plan.'),
('Goblin Giant','Sparky','SYNERGY',10,'Goblin Giant tanks and provides spear support for Sparky pushes.'),
('Goblin Giant','Mini P.E.K.K.A','SYNERGY',6,'Mini P.E.K.K.A defends tanks while Goblin Giant counterpushes.'),
('Goblin Giant','Lightning','SYNERGY',7,'Lightning clears buildings and ranged defenders for Goblin Giant.'),
('Goblin Giant','Rage','SYNERGY',6,'Rage increases Goblin Giant push pressure.'),
('Goblin Giant','Bats','SYNERGY',5,'Bats add cheap pressure around Goblin Giant.'),
('Goblin Giant','Zap','SYNERGY',6,'Zap protects Sparky and Goblin Giant from swarms and resets.'),
('X-Bow','Archers','SYNERGY',7,'Archers support X-Bow defense and anti-air.'),
('X-Bow','Knight','SYNERGY',7,'Knight tanks cheaply for X-Bow and supports defense.'),
('X-Bow','Fireball','SYNERGY',8,'Fireball removes medium troops defending X-Bow.'),
('X-Bow','The Log','SYNERGY',8,'The Log clears ground swarms and knocks back X-Bow counters.'),
('X-Bow','Ice Spirit','SYNERGY',6,'Ice Spirit cycles and stalls defenders for X-Bow.'),
('X-Bow','Skeletons','SYNERGY',6,'Skeletons support cheap X-Bow cycle defense.'),
('X-Bow','Rocket','SYNERGY',7,'Rocket gives X-Bow control decks a finishing spell.'),
('X-Bow','Earthquake','COUNTER_SYNERGY',-8,'Earthquake is a strong answer to buildings and conflicts with X-Bow plans.'),
('Mortar','Archers','SYNERGY',6,'Archers provide cheap anti-air support for Mortar.'),
('Mortar','Knight','SYNERGY',6,'Knight tanks for Mortar and defends cheaply.'),
('Mortar','Skeleton King','SYNERGY',7,'Skeleton King benefits from swarm-heavy Mortar decks.'),
('Mortar','Goblin Gang','SYNERGY',7,'Goblin Gang pressures and protects Mortar from tanks.'),
('Mortar','Fireball','SYNERGY',6,'Fireball removes medium Mortar defenders.'),
('Mortar','Bats','SYNERGY',5,'Bats add cheap defense and bait pressure around Mortar.'),
('Mortar','Earthquake','COUNTER_SYNERGY',-7,'Earthquake conflicts with building-based siege plans.'),
('Battle Ram','Royal Ghost','SYNERGY',8,'Royal Ghost adds bridge spam pressure with Battle Ram.'),
('Battle Ram','Magic Archer','SYNERGY',7,'Magic Archer punishes defensive placements against Battle Ram.'),
('Battle Ram','Electro Wizard','SYNERGY',7,'Electro Wizard resets defensive units and supports bridge spam.'),
('Battle Ram','Poison','SYNERGY',6,'Poison controls troops defending Battle Ram.'),
('Battle Ram','Zap','SYNERGY',5,'Zap resets and clears small defenders for Battle Ram.'),
('Bandit','Royal Ghost','SYNERGY',7,'Bandit and Royal Ghost create constant bridge pressure.'),
('Bandit','Magic Archer','SYNERGY',6,'Magic Archer supports bridge spam punish patterns.'),
('Ram Rider','Bandit','SYNERGY',7,'Bandit supports Ram Rider bridge pressure.'),
('Ram Rider','Magic Archer','SYNERGY',7,'Magic Archer punishes defenses against Ram Rider.'),
('Ram Rider','Giant Snowball','SYNERGY',6,'Giant Snowball supports Ram Rider connections.'),
('P.E.K.K.A','Bandit','SYNERGY',8,'Bandit turns P.E.K.K.A defenses into bridge pressure.'),
('P.E.K.K.A','Magic Archer','SYNERGY',8,'Magic Archer supports P.E.K.K.A bridge spam and punish angles.'),
('P.E.K.K.A','Electro Wizard','SYNERGY',8,'Electro Wizard protects P.E.K.K.A from Inferno and air threats.'),
('P.E.K.K.A','Poison','SYNERGY',7,'Poison clears swarm and support around P.E.K.K.A pushes.'),
('P.E.K.K.A','Zap','SYNERGY',6,'Zap resets Inferno threats against P.E.K.K.A.'),
('Graveyard','Poison','SYNERGY',10,'Poison clears troops used to defend Graveyard.'),
('Graveyard','Freeze','SYNERGY',8,'Freeze can secure Graveyard damage by stopping defenders.'),
('Graveyard','Baby Dragon','SYNERGY',8,'Baby Dragon tanks and splashes defenders for Graveyard.'),
('Graveyard','Tornado','SYNERGY',7,'Tornado groups defenders away from Graveyard skeletons.'),
('Graveyard','Knight','SYNERGY',7,'Knight is a cheap tank for Graveyard pushes.'),
('Graveyard','Valkyrie','SYNERGY',7,'Valkyrie tanks and clears ground swarms during Graveyard.'),
('Royal Hogs','Earthquake','SYNERGY',10,'Earthquake damages buildings that pull Royal Hogs.'),
('Royal Hogs','Fireball','SYNERGY',7,'Fireball clears medium defenders against Royal Hogs.'),
('Royal Hogs','Zappies','SYNERGY',7,'Zappies defend and support Royal Hogs counterpressure.'),
('Royal Hogs','Royal Recruits','SYNERGY',8,'Royal Recruits and Royal Hogs create split-lane pressure.'),
('Royal Hogs','Flying Machine','SYNERGY',7,'Flying Machine supports Royal Hogs from range.'),
('Royal Hogs','Barbarian Hut','COUNTER_SYNERGY',-6,'Royal Hogs and Barbarian Hut make the deck too structure-heavy.'),
('Three Musketeers','Royal Ghost','SYNERGY',7,'Royal Ghost supports split-lane Three Musketeers pressure.'),
('Three Musketeers','Battle Ram','SYNERGY',8,'Battle Ram pressures opposite lane with split Three Musketeers.'),
('Three Musketeers','Bandit','SYNERGY',7,'Bandit supports split-lane pressure after Three Musketeers.'),
('Three Musketeers','Elixir Collector','SYNERGY',8,'Elixir Collector helps fund Three Musketeers.'),
('Three Musketeers','Heal Spirit','SYNERGY',6,'Heal Spirit supports grouped Musketeer pressure.'),
('Three Musketeers','Rocket','COUNTER_SYNERGY',-8,'Rocket hard-counters Three Musketeers and suggests matchup risk.'),
('Sparky','Giant','SYNERGY',8,'Giant tanks while Sparky threatens defensive troops.'),
('Sparky','Goblin Giant','SYNERGY',10,'Goblin Giant protects and tanks for Sparky.'),
('Sparky','Tornado','SYNERGY',7,'Tornado groups troops for Sparky blast value.'),
('Sparky','Rage','SYNERGY',6,'Rage increases Sparky push threat.'),
('Sparky','Electro Dragon','COUNTER_SYNERGY',-8,'Electro Dragon repeatedly resets Sparky.'),
('Inferno Dragon','Tornado','SYNERGY',7,'Tornado pulls tanks into Inferno Dragon damage.'),
('Inferno Dragon','Mega Minion','SYNERGY',6,'Mega Minion adds reliable air defense next to Inferno Dragon.'),
('Inferno Dragon','Miner','SYNERGY',5,'Miner pressures while Inferno Dragon controls tanks.'),
('Inferno Dragon','Electro Wizard','COUNTER_SYNERGY',-8,'Electro Wizard resets Inferno Dragon damage.'),
('Inferno Tower','Rocket','SYNERGY',6,'Rocket gives control decks finishing damage with Inferno Tower defense.'),
('Inferno Tower','Princess','SYNERGY',6,'Princess pressures while Inferno Tower anchors bait defense.'),
('Inferno Tower','Electro Spirit','COUNTER_SYNERGY',-5,'Electro Spirit can reset Inferno Tower at low cost.'),
('Tesla','Firecracker','SYNERGY',7,'Tesla and Firecracker combine hidden building defense with ranged splash.'),
('Tesla','Archers','SYNERGY',6,'Archers support Tesla with flexible anti-air coverage.'),
('Tesla','Ice Spirit','SYNERGY',5,'Ice Spirit stalls units inside Tesla range.'),
('Bomb Tower','Tornado','SYNERGY',7,'Tornado pulls ground troops into Bomb Tower splash.'),
('Bomb Tower','Miner','SYNERGY',5,'Bomb Tower stabilizes Miner control decks.'),
('Cannon','Musketeer','SYNERGY',6,'Cannon and Musketeer form a cheap defensive core.'),
('Cannon','Ice Spirit','SYNERGY',5,'Ice Spirit stalls threats inside Cannon range.'),
('Cannon','Skeletons','SYNERGY',5,'Skeletons distract threats while Cannon deals damage.'),
('Firecracker','Skeletons','SYNERGY',5,'Skeletons distract while Firecracker deals long-range splash.'),
('Firecracker','Ice Spirit','SYNERGY',5,'Ice Spirit stalls troops for Firecracker shots.'),
('Firecracker','Earthquake','SYNERGY',6,'Earthquake and Firecracker support cycle decks against buildings and swarms.'),
('Musketeer','Ice Golem','SYNERGY',6,'Ice Golem tanks cheaply for Musketeer counterpushes.'),
('Musketeer','Skeletons','SYNERGY',5,'Skeletons distract threats targeting Musketeer.'),
('Musketeer','Fireball','COUNTER_SYNERGY',-5,'Fireball is a common answer to Musketeer and indicates matchup risk.'),
('Magic Archer','Miner','SYNERGY',7,'Miner pressure forces placements that Magic Archer can punish.'),
('Magic Archer','Wall Breakers','SYNERGY',7,'Wall Breakers pressure while Magic Archer punishes compact defenses.'),
('Magic Archer','Fireball','COUNTER_SYNERGY',-5,'Fireball is a common direct answer to Magic Archer.'),
('Executioner','Baby Dragon','SYNERGY',6,'Executioner and Baby Dragon give heavy splash and air coverage.'),
('Executioner','Freeze','SYNERGY',5,'Freeze can hold troops inside Executioner splash lines.'),
('Baby Dragon','Tornado','SYNERGY',9,'Tornado groups troops for Baby Dragon splash damage.'),
('Baby Dragon','Graveyard','SYNERGY',8,'Baby Dragon tanks and controls swarm defenders for Graveyard.'),
('Baby Dragon','Poison','SYNERGY',7,'Poison and Baby Dragon control Graveyard defense.'),
('Electro Wizard','P.E.K.K.A','SYNERGY',8,'Electro Wizard protects P.E.K.K.A from Inferno threats.'),
('Electro Wizard','Battle Ram','SYNERGY',7,'Electro Wizard supports bridge spam by resetting defenders.'),
('Electro Wizard','Zap','SYNERGY',5,'Zap and Electro Wizard provide layered reset utility.'),
('Zappies','Royal Hogs','SYNERGY',7,'Zappies support Royal Hogs with defensive control.'),
('Zappies','Fireball','COUNTER_SYNERGY',-5,'Fireball punishes grouped Zappies.'),
('Mother Witch','Royal Giant','SYNERGY',7,'Mother Witch punishes swarms used against Royal Giant.'),
('Mother Witch','Fireball','COUNTER_SYNERGY',-5,'Fireball is a common answer to Mother Witch.'),
('Phoenix','Monk','SYNERGY',7,'Monk protects Phoenix support from ranged damage.'),
('Phoenix','Miner','SYNERGY',6,'Miner pressures while Phoenix supports from air.'),
('Phoenix','Lightning','COUNTER_SYNERGY',-5,'Lightning removes Phoenix and other high-value support.'),
('Monk','Graveyard','SYNERGY',7,'Monk tanks and protects Graveyard pushes.'),
('Monk','Phoenix','SYNERGY',7,'Monk and Phoenix create durable control counterpushes.'),
('Monk','Rocket','COUNTER_SYNERGY',-6,'Rocket can punish expensive Monk support clusters.'),
('Little Prince','Goblin Giant','SYNERGY',6,'Little Prince supports Goblin Giant with ranged damage.'),
('Little Prince','Royal Giant','SYNERGY',6,'Little Prince gives Royal Giant decks cheap ranged support.'),
('Little Prince','Fireball','COUNTER_SYNERGY',-5,'Fireball is a common answer to Little Prince.'),
('Skeleton King','Graveyard','SYNERGY',8,'Skeleton King benefits from skeleton pressure and tanks for Graveyard.'),
('Skeleton King','Skeleton Army','SYNERGY',7,'Skeleton Army charges Skeleton King and baits spells.'),
('Skeleton King','Tombstone','SYNERGY',7,'Tombstone feeds Skeleton King ability value.'),
('Skeleton King','Poison','COUNTER_SYNERGY',-5,'Poison clears Skeleton King support swarms.'),
('Golden Knight','Tornado','SYNERGY',8,'Tornado lines up Golden Knight dash chains.'),
('Golden Knight','Three Musketeers','SYNERGY',6,'Golden Knight supports split pressure in expensive decks.'),
('Golden Knight','P.E.K.K.A','COUNTER_SYNERGY',-5,'Golden Knight and P.E.K.K.A can overload the deck with ground melee cost.'),
('Mighty Miner','Wall Breakers','SYNERGY',7,'Mighty Miner tanks and threatens lane swaps with Wall Breakers.'),
('Mighty Miner','Miner','SYNERGY',6,'Dual Miner-style pressure supports control chip decks.'),
('Mighty Miner','Electro Wizard','COUNTER_SYNERGY',-5,'Electro Wizard resets Mighty Miner ramp damage.'),
('Boss Bandit','Royal Ghost','SYNERGY',7,'Boss Bandit and Royal Ghost stack fast bridge pressure.'),
('Boss Bandit','Battle Ram','SYNERGY',7,'Boss Bandit supports bridge spam pressure with Battle Ram.'),
('Boss Bandit','P.E.K.K.A','SYNERGY',6,'Boss Bandit can counterpressure after P.E.K.K.A defense.'),
('Rune Giant','Sparky','SYNERGY',7,'Rune Giant support helps Sparky pushes become more threatening.'),
('Rune Giant','Goblin Giant','SYNERGY',7,'Rune Giant supports a tank-heavy pressure plan with Goblin Giant.'),
('Rune Giant','Berserker','SYNERGY',6,'Rune Giant support pairs well with fast melee pressure.'),
('Spirit Empress','Phoenix','SYNERGY',7,'Spirit Empress and Phoenix create strong air-support pressure.'),
('Spirit Empress','Tornado','SYNERGY',6,'Tornado helps Spirit Empress control grouped troops.'),
('Spirit Empress','Lightning','SYNERGY',6,'Lightning removes high-value air counters for Spirit Empress.'),
('Berserker','Goblin Drill','SYNERGY',5,'Berserker adds cheap ground pressure next to Drill cycle.'),
('Berserker','Miner','SYNERGY',5,'Miner tanks for Berserker and creates cheap pressure.'),
('Berserker','Rune Giant','SYNERGY',6,'Rune Giant support improves Berserker pressure.'),
('Goblinstein','Lightning','SYNERGY',7,'Lightning clears buildings and support against Goblinstein pressure.'),
('Goblinstein','Tornado','SYNERGY',7,'Tornado helps Goblinstein control defensive formations.'),
('Goblinstein','Phoenix','SYNERGY',6,'Phoenix supports Goblinstein pushes with air pressure.'),
('Goblin Machine','Goblin Giant','SYNERGY',6,'Goblin Machine adds ranged support to Goblin Giant pushes.'),
('Goblin Machine','Goblin Drill','SYNERGY',5,'Goblin Machine supports Goblin pressure decks.'),
('Goblin Demolisher','Goblin Drill','SYNERGY',6,'Goblin Demolisher helps pressure ground defenses around Drill.'),
('Goblin Demolisher','Goblin Giant','SYNERGY',6,'Goblin Demolisher supports Goblin Giant bridge pressure.'),
('Suspicious Bush','Miner','SYNERGY',6,'Suspicious Bush adds cheap surprise pressure with Miner.'),
('Suspicious Bush','Wall Breakers','SYNERGY',6,'Suspicious Bush and Wall Breakers create cheap lane pressure.'),
('Goblin Curse','Goblin Barrel','SYNERGY',6,'Goblin Curse supports swarm pressure and bait patterns.'),
('Goblin Curse','Goblin Drill','SYNERGY',6,'Goblin Curse pressures defensive troops around Drill.'),
('Void','Miner','SYNERGY',6,'Void supports Miner chip by punishing defensive placements.'),
('Void','Goblin Drill','SYNERGY',6,'Void punishes compact answers to Goblin Drill.'),
('Void','Lava Hound','SYNERGY',6,'Void removes high-value anti-air defending Lava pushes.'),
('Arrows','Minion Horde','COUNTER_SYNERGY',-8,'Arrows directly counter Minion Horde.'),
('Arrows','Goblin Gang','COUNTER_SYNERGY',-7,'Arrows efficiently remove Goblin Gang.'),
('Arrows','Princess','COUNTER_SYNERGY',-6,'Arrows remove Princess at range.'),
('The Log','Skeleton Army','COUNTER_SYNERGY',-8,'The Log clears Skeleton Army efficiently.'),
('The Log','Goblin Barrel','COUNTER_SYNERGY',-9,'The Log is the primary answer to Goblin Barrel.'),
('The Log','Princess','COUNTER_SYNERGY',-6,'The Log removes Princess cheaply.'),
('Zap','Bats','COUNTER_SYNERGY',-7,'Zap clears Bats cheaply.'),
('Zap','Skeleton Army','COUNTER_SYNERGY',-7,'Zap clears Skeleton Army cheaply.'),
('Giant Snowball','Balloon','COUNTER_SYNERGY',-6,'Giant Snowball knocks Balloon back and slows it.'),
('Fireball','Flying Machine','COUNTER_SYNERGY',-7,'Fireball removes Flying Machine.'),
('Fireball','Three Musketeers','COUNTER_SYNERGY',-8,'Fireball punishes Three Musketeers for positive value.'),
('Poison','Graveyard','COUNTER_SYNERGY',-8,'Poison is a common defensive answer to Graveyard.'),
('Poison','Skeleton Army','COUNTER_SYNERGY',-7,'Poison clears swarm defenses over time.'),
('Rocket','Sparky','COUNTER_SYNERGY',-8,'Rocket removes Sparky for reliable value.'),
('Lightning','Inferno Tower','COUNTER_SYNERGY',-7,'Lightning removes or weakens Inferno Tower against tanks.'),
('Lightning','Musketeer','COUNTER_SYNERGY',-6,'Lightning removes Musketeer and other ranged supports.'),
('Earthquake','Tesla','COUNTER_SYNERGY',-8,'Earthquake is a strong building answer to Tesla.'),
('Earthquake','Cannon','COUNTER_SYNERGY',-8,'Earthquake is a strong building answer to Cannon.'),
('Earthquake','X-Bow','COUNTER_SYNERGY',-9,'Earthquake heavily punishes X-Bow.'),
('Earthquake','Mortar','COUNTER_SYNERGY',-8,'Earthquake heavily damages Mortar.'),
('Tornado','Hog Rider','COUNTER_SYNERGY',-7,'Tornado can activate king tower against Hog Rider.'),
('Tornado','Goblin Barrel','COUNTER_SYNERGY',-6,'Tornado can activate king tower against Goblin Barrel.'),
('Hunter','Balloon','COUNTER_SYNERGY',-7,'Hunter deals high burst damage to Balloon.'),
('Musketeer','Balloon','COUNTER_SYNERGY',-6,'Musketeer is a reliable ranged answer to Balloon.'),
('Tesla','Balloon','COUNTER_SYNERGY',-7,'Tesla pulls and damages Balloon.'),
('Inferno Tower','Golem','COUNTER_SYNERGY',-8,'Inferno Tower melts Golem if not reset.'),
('Inferno Dragon','Giant','COUNTER_SYNERGY',-7,'Inferno Dragon melts Giant if protected.'),
('Mini P.E.K.K.A','Hog Rider','COUNTER_SYNERGY',-6,'Mini P.E.K.K.A quickly removes Hog Rider.'),
('P.E.K.K.A','Mega Knight','COUNTER_SYNERGY',-7,'P.E.K.K.A is a strong answer to Mega Knight.'),
('Valkyrie','Goblin Drill','COUNTER_SYNERGY',-7,'Valkyrie clears Goblin Drill spawns effectively.'),
('Bomb Tower','Royal Hogs','COUNTER_SYNERGY',-7,'Bomb Tower is a strong defensive answer to Royal Hogs.'),
('Barbarians','Royal Giant','COUNTER_SYNERGY',-6,'Barbarians surround and damage Royal Giant.'),
('Skeleton Army','Prince','COUNTER_SYNERGY',-7,'Skeleton Army overwhelms Prince without spell support.'),
('Guards','Prince','COUNTER_SYNERGY',-6,'Guards block Prince charge with shields.'),
('Electro Spirit','Bats','COUNTER_SYNERGY',-6,'Electro Spirit chains through Bats.'),
('Baby Dragon','Skeleton Army','COUNTER_SYNERGY',-6,'Baby Dragon splash clears Skeleton Army.'),
('Executioner','Minion Horde','COUNTER_SYNERGY',-7,'Executioner splash removes Minion Horde.'),
('Wizard','Minion Horde','COUNTER_SYNERGY',-7,'Wizard splash removes Minion Horde.'),
('Bowler','Royal Hogs','COUNTER_SYNERGY',-6,'Bowler knockback controls Royal Hogs.'),
('Fisherman','Royal Giant','COUNTER_SYNERGY',-6,'Fisherman pulls Royal Giant away from tower.'),
('Fisherman','Giant','COUNTER_SYNERGY',-6,'Fisherman pulls Giant away and disrupts pushes.')
) AS v(card_a, card_b, type, weight, explanation)
JOIN cards a ON a.name = v.card_a
JOIN cards b ON b.name = v.card_b
WHERE NOT EXISTS (
    SELECT 1 FROM card_synergies existing
    WHERE existing.card_a_id = a.id AND existing.card_b_id = b.id
);
